/**
 * The KPI catalogue lives in src/erp/kpi.ts. This module mirrors it for the
 * seed script so the SQL engine and the UI agree on names, polarity,
 * thresholds and — critically — the action attached to each breach.
 *
 * Tuple order: code, name, name_en, category, polarity, unit, formula,
 *              benchmark, warn, critical, action, sort_order
 */
export type DefTuple = [string, string, string, string, string, string, string,
  number | null, number | null, number | null, string, number];

export const DEFS: DefTuple[] = [
  ['net_sales_30d', 'صافي المبيعات (30 يوم)', 'Net Sales 30d', 'sales', 'higher', 'currency',
    'SUM(base_subtotal) WHERE status=completed AND created_at >= now()-30d',
    null, null, null, 'انخفاض عن الشهر السابق: افحص أداء الفروع والأصناف الراكدة', 10],
  ['sales_growth_mom', 'النمو الشهري', 'MoM Sales Growth', 'sales', 'higher', 'percent',
    '((sales_this_month - sales_last_month) / sales_last_month) * 100',
    5, 0, -10, 'تراجع: افحص الحركة اليومية والأسبوع الأخير تحديداً', 11],
  ['avg_basket_value', 'متوسط قيمة الفاتورة', 'Average Basket Value', 'sales', 'higher', 'currency',
    'SUM(base_total) / COUNT(DISTINCT invoice_id)',
    null, null, null, 'انخفاضها: فعّل البيع المقترح أو باقات تشجيع الكمية', 12],
  ['units_per_transaction', 'متوسط عدد القطع/الفاتورة', 'Units per Transaction', 'sales', 'higher', 'ratio',
    'SUM(item.qty) / COUNT(DISTINCT invoice_id)',
    2.0, 1.5, 1.0, 'قيمة منخفضة: كل قطعة تُقلّص هامش الفاتورة — ارفع الحافز للبيع الإضافي', 13],
  ['selling_days', 'أيام البيع الفعّالة/30', 'Active Selling Days', 'sales', 'higher', 'count',
    'COUNT(DISTINCT created_at::date) WHERE created_at >= now()-30d',
    26, 20, 14, 'أيام مغلقة دون بيع: تحقق من ساعات العمل وتغطية الفروع', 14],

  ['gross_margin_pct', 'هامش الربح الإجمالي', 'Gross Margin %', 'margin', 'higher', 'percent',
    '(SUM(base_subtotal) - SUM(item.qty*item.cost)) / SUM(base_subtotal) * 100',
    30, 22, 15, 'هامش منخفض: راجع تكلفة الشراء وسعر البيع — لا ترفع السعر قبل تثبيت التكلفة', 20],
  ['price_realisation_pct', 'نسبة تحقيق السعر', 'Price Realisation %', 'margin', 'higher', 'percent',
    'AVG(item.price / products.unit_price) * 100',
    95, 88, 80, 'تحقيق منخفض مع حجم ثابت: تسرّب هوامش عبر خصم غير مصرّح به', 21],
  ['discount_ratio_pct', 'نسبة الخصومات الممنوحة', 'Discount Ratio %', 'margin', 'lower', 'percent',
    'SUM(discount) / SUM(base_subtotal) * 100',
    5, 10, 18, 'نسبة مرتفعة: قصر صلاحية الخصم على مدير المبيعات وراجع سجل الصلاحيات', 22],

['inventory_turnover', 'دوران المخزون', 'Inventory Turnover', 'inventory', 'higher', 'ratio',
    'COGS(365d) / AVG(inventory_value)',
    6, 4, 2, 'دوران منخفض: المال محبوس في بضاعة لا تتحرك', 30],
  ['dio_days', 'مدة بقاء المخزون', 'Days Inventory Outstanding', 'inventory', 'lower', 'days',
    'AVG(inventory_value) / COGS(365d) * 365',
    45, 75, 120, 'مدة طويلة: جمّد إعادة الطلب وبِعِ الراكد قبل أن يلتهم السيولة', 31],
  ['dead_stock_pct', 'نسبة المخزون الراكد', 'Dead Stock %', 'inventory', 'lower', 'percent',
    'SUM(cost*stock WHERE no sale in 90d) / SUM(cost*stock) * 100',
    15, 25, 40, 'نسبة مرتفعة: خفّض إعادة الطلب لهذه الأصناف وراجع خطة الشراء', 32],
  ['stockout_risk_count', 'أصناف تحت حد الطلب', 'Stock-out Risk Items', 'inventory', 'lower', 'count',
    'COUNT(products WHERE stock <= reorder_point)',
    0, 5, 15, 'إنشاء أوامر شراء فورية — كل يوم نقص يعني مبيعات ضائعة', 33],
  ['inventory_accuracy_pct', 'دقة المخزون', 'Inventory Accuracy %', 'inventory', 'higher', 'percent',
    '(1 - SUM(ABS(variance_qty)) / SUM(system_qty)) * 100',
    98, 95, 90, 'دقة منخفضة: جرد دوري متصاعد — فروقات الجرد تفسد قرار الشراء كله', 34],
  ['shrinkage_rate_pct', 'نسبة التلف والفقد', 'Shrinkage Rate %', 'inventory', 'lower', 'percent',
    'SUM(shrink_value) / SUM(counted_value) * 100',
    1, 2, 4, 'فقد مرتفع: راجع إجراءات الاستلام والإرجاع — قد يكون تلاعباً', 35],
  ['aging_stock_pct', 'نسبة مخزون قرب الانتهاء', 'Near-Expiry Stock %', 'inventory', 'lower', 'percent',
    'SUM(quantity*cost WHERE expiry within 60d) / SUM(quantity*cost) * 100',
    3, 8, 15, 'تصريف فوري بعرض تخفيضي منظّم أو إتلاف موثّق', 36],

['dso_days', 'مدة تحصيل الذمم', 'Days Sales Outstanding', 'receivable', 'lower', 'days',
    'AVG(AR outstanding) / (net_sales_365 / 365)',
    35, 50, 75, 'تحصيل بطيء: شدّد سياسة الائتمان ووقف البيع الآجل للمتخلفين', 40],
  ['overdue_ar_pct', 'نسبة الذمم المتأخرة', 'Overdue AR %', 'receivable', 'lower', 'percent',
    'SUM(AR outstanding WHERE due_date < today) / SUM(AR outstanding) * 100',
    10, 20, 35, 'متأخرات عالية: جدولة تحصيل فورية ووقف سقف ائتماني جديد', 41],
  ['credit_utilisation_pct', 'استخدام سقف الائتمان', 'Credit Utilisation %', 'receivable', 'lower', 'percent',
    'SUM(customer outstanding) / SUM(customer credit_limit) * 100',
    50, 75, 90, 'استخدام مرتفع: خفّض السقوف — خطر التعثر مرتفع', 42],
  ['customer_retention_pct', 'معدل الاحتفاظ بالعملاء', 'Customer Retention %', 'receivable', 'higher', 'percent',
    'repeat customers / total active customers * 100',
    40, 25, 15, 'احتفاظ منخفض: اكسب سبب التخلّي — عروض ولاء مستهدفة', 43],

  ['dpo_days', 'مدة سداد الموردين', 'Days Payable Outstanding', 'payable', 'target', 'days',
    'AVG(AP outstanding) / (purchases_365 / 365)',
    30, 45, 60, 'سداد متأخر: خطر قطع التوريد — راجع الالتزامات التعاقدية', 45],
  ['overdue_ap_pct', 'نسبة المستحقات للموردين', 'Overdue AP %', 'payable', 'lower', 'percent',
    'SUM(AP outstanding WHERE due_date < today) / SUM(AP outstanding) * 100',
    5, 15, 30, 'مستحقات متأخرة: سدّد فوراً لتفادي تعليق التوريد', 46],

  ['ccc_days', 'دورة التحويل النقدي', 'Cash Conversion Cycle', 'cash', 'lower', 'days',
    'DIO + DSO - DPO',
    15, 40, 70, 'دورة طويلة: المال محبوس في المخزون والذمم — تمويل ضروري', 50],
  ['cash_sales_ratio_pct', 'نسبة المبيعات النقدية', 'Cash Sales Ratio %', 'cash', 'higher', 'percent',
    'SUM(total WHERE payment_method = cash) / SUM(total) * 100',
    60, 45, 30, 'نسبة نقدية منخفضة: وجّه الخصم النقدي لتحسين دورة التحصيل', 51],
  ['cash_variance_abs', 'فروقات الصندوق', 'Cash Variance', 'cash', 'lower', 'currency',
    'SUM(ABS(cash_counts.variance))',
    0, 50, 200, 'فروقات نقدية: جرد كل وردية فوراً — الفروقات الصغيرة التراكمية تعني مشكلة', 52],

  ['sales_per_employee', 'المبيعات/موظف', 'Sales per Employee', 'hr', 'higher', 'currency',
    'net_sales_30d / active_employees',
    null, null, null, 'قياس إنتاجية — قارنه بمتوسط القطاع قبل زيادة عدد الموظفين', 55],
  ['attendance_rate_pct', 'نسبة الحضور', 'Attendance Rate %', 'hr', 'higher', 'percent',
    'present_days / (present + absent) * 100',
    92, 85, 75, 'غياب مرتفع: راجع الحافز والظروف — الغياب المبكر يقلب التكلفة', 56],
  ['fx_exposure_pct', 'نسبة التعرض لفروق الصرف', 'FX Exposure %', 'fx', 'lower', 'percent',
    'SUM(ABS(base_total-total) WHERE currency != base) / SUM(base_total) * 100',
    20, 35, 50, 'تعرض مرتفع: أغلق المركز فوراً أو تحوّط — فروق الصرف غير مُسعَّرة', 60],
];